# Generated by Django 5.2 on 2026-05-08 11:38

import core.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=244)),
                ('dob', models.DateField()),
                ('gender', models.CharField(max_length=1)),
                ('locality', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('pin', models.PositiveBigIntegerField(help_text='The pin length mimimum 7 charecter', validators=[core.models.validate_pin_length])),
                ('division', models.CharField(choices=[('Dhaka', 'Dhaka'), ('Chattogram', 'Chattogram'), ('Rajshahi', 'Rajshahi'), ('Khulna', 'Khulna'), ('Barisal', 'Barisal'), ('Sylhet', 'Sylhet'), ('Rangpur', 'Rangpur'), ('Mymensingh', 'Mymensingh')], max_length=60)),
                ('mobile', models.CharField(help_text='Enter a 11 digit mobile_number ', max_length=11, validators=[django.core.validators.RegexValidator(message='Enter a valid 11 digit number', regex='^\\d{11}$')])),
                ('email', models.EmailField(max_length=89)),
                ('job_city', models.CharField(max_length=78)),
                ('profile_image', models.ImageField(blank=True, upload_to='profile_image')),
                ('my_file', models.FileField(blank=True, upload_to='doc')),
            ],
        ),
    ]
