# Generated by Django 5.2 on 2026-04-07 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Underconstraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_underconstraction', models.BooleanField(default=False)),
                ('uc_note', models.TextField(max_length=255)),
                ('uc_duration', models.DateTimeField(blank=True, help_text='Enter the duration time', null=True)),
                ('uc_update', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
